### ISSUE TITLE
Research & implement open weight models

### ISSUE THREAD

**Issue by sayantikabanik** [sayantikabanik/DataJourney#32]
### Describe the issue

Ride the chatter and implement a open vs closed source GenAI model

**Comment by sayantikabanik** [comment]
### TODO(s)

- [ ] implement 
- [ ] dockerize the solution 
- [ ] research on the workflows that can be used for monitoring 
- [ ] implement explainability 
- [ ] ride the chatter and add the business values 
- [ ] more words -> based on the various personas 
- [ ] ethics chat
- [ ] do(s)/ dont'(s)
- [ ] collaborate

**Comment by sayantikabanik** [comment]
Rethinking!!

**Comment by sayantikabanik** [comment]
Pushing to backlog! closing the issue
